### PR TITLE
Ability added to provide a custom token factory

### PR DESCRIPTION
**Pull request by iainmckay**
We're trying this bundle and our app requires a specific auth token to be created. This PR adds the ability to provide a custom token factory.

### CODE REVIEW

**Comment by iainmckay** [comment]
Thank you for fixing the failing tests. I was in the process of fixing them :)

**Comment by tmilos** [comment]
Sure, no problem, thank you for contributing. 
I made a small change to the factory, removed the ``SamlSpTokenInterface`` you added since it wasn't really used, and depend on Symfony's ``TokenInterface``. Guess that suites your needs, you can use which ever token class you want. In the yet to be written logout bundle we would need NameID and SessionIndex, but think they can be stored in token attributes.

**Comment by tmilos** [comment]
Btw, feel free to add yourself to the [CONTRIBUTORS.md](https://github.com/lightSAML/SpBundle/blob/master/CONTRIBUTORS.md) file

**Comment by iainmckay** [comment]
Sure, that works for me.

**Pull request merged**
