### PR TITLE
Fix project setup

### PR DESCRIPTION
**Pull request by cb8**
As discussed in lightsaml/lightsaml#3 and lightsaml/lightsaml#6.

### CODE REVIEW

**Comment by cb8** [comment]
Update: I think the tests are now solely failing due to lightSAML/SymfonyBridgeBundle#2.

**Comment by tmilos** [comment]
@cb8 composer is memorying out after your changes, in PR #5 I continued on your changes, and have tried first to fix it with with [phpenv config-rm and phpenv config-add](https://github.com/travis-ci/travis-ci/issues/1697) but out of memory still occurred. Then I replaced all require-dev deps you added with symfony/symofny and composer managed to pass below 1G and tests passed. 

Guess we could merge now #5 and close this PR, but first let me ask you two questions
1) why did you increase symfony version from 2.3 to 2.6?
2) why should composer prefer source? Dist is faster to install

**Comment by cb8** [comment]
1) I'm sorry, I misinterpreted a PHPUnit error during a local test run. I forgot to clear the cache which is used for the functional test cases. I lowered the requirements back to 2.3 in c7a581a.

2) Yes, the installation would be faster. AFAIK `--prefer-dist` leads to more Github API requests which sometimes result in some issues regarding authentication/DoS protection.

In 97787b6 I removed the `memory_limit` for PHP which solves the Composer issue. We are now limited to 3 GB (Travis VM limit).

**Comment by tmilos** [comment]
Merged with #5

**Pull request merged**
